name: CD Prod (deploy to CloudFlare)

on:
  workflow_dispatch:

env:
  #  Can be accessed in the app with {import.meta.env.VITE_BUILD_ENVIRONMENT}
  VITE_BUILD_ENVIRONMENT: Production build

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    environment:
      name: production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build -- --base=/
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 6366c6999e5353a03edd4b5b87499b69
          projectName: github-actions
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
