name: CD Prod (deploy to CloudFlare)

on:
  workflow_dispatch:    

jobs:
  deploy:
    environment:
      name: prod
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "actions"
          directory: "dist"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
