name: CD Prod (deploy to CloudFlare)

on:
  workflow_dispatch:    

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    environment:
      name: cloudflare-pages2
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: github-actions
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
