name: CI Prod (test, lint & build)

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "lib/**"

jobs:
  test:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          # https://github.com/actions/setup-node#caching-global-packages-data
          # node-version: 18
          cache: "npm"
      - name: "Install Dependencies"
        run: npm ci
      - name: "Run Tests"
        run: npm run test

  lint:
    name: "Run linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: "Install Dependencies"
        run: npm i
      - name: "Run Linter"
        run: npm run lint

  build:
    name: "Run build"
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: "Install Dependencies"
        run: npm i
      - name: "Run build"
        run: npm run build

  # deploy:
  #   environment:
  #     name: prod
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   permissions:
  #     contents: read
  #     deployments: write
  #   name: Deploy to Cloudflare Pages
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Publish
  #       uses: cloudflare/pages-action@1
  #       with:
  #         apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  #         accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  #         projectName: "Actions"
  #         directory: "dist"
  #         gitHubToken: ${{ secrets.GITHUB_TOKEN }}
