name: JavaScript Job

on:
  workflow_dispatch:
    # Input in the GitHub actions gui
    inputs:
      who_to_greet: # id of input
        description: "Who to greet"
        required: true
        default: "RopaOlle"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm ci
      - name: Hello world action step
        uses: ./.github/actions/javascript
        id: hello
        with:
          #  Input from `/home/olle/GITHOME/actions/.github/actions/javascript/action.yml`
          who-to-greet: ${{ github.event.inputs.who_to_greet }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: |
          ls -la
          pwd
          echo "The time was ${{ steps.hello.outputs.time }}"
