name: JavaScript Job

on:
  workflow_dispatch:
    inputs:
      PR_number:
        description: "Pull request number"
        required: false
      who_to_greet: # id of input
        description: "Who to greet"
        required: true
        default: "World"
      who_to_greet_b: # id of input
        description: "Who to greet b"
        required: true
        default: "World b"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm ci
      - name: Hello world action step
        uses: ./.github/actions/javascript
        id: hello
        with:
          who-to-greet: "Mona the Octocat"
          who_to_greet: ${{ github.event.inputs.who_to_greet }}
          who_to_greet_b:
      # Use the output from the `hello` step
      - name: Get the output time
        run: |
          ls -la
          pwd
          echo "The time was ${{ steps.hello.outputs.time }}"
